config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  resources :main_courses
  root 'home#base_my_courses'
  get 'home/about'
  get 'home/index_students'
  get 'main_courses/index'
  post 'main_courses/enroll'
  post 'main_courses/deenroll'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable


  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

          has_many :subscriptions
          has_many :main_courses, through: :subscriptions
         
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ApplicationRecord
end

app/models/main_course.rb
class MainCourse < ApplicationRecord
    has_many :subscriptions
    has_many :admins, through: :subscriptions 
end

app/models/subscription.rb
class Subscription < ApplicationRecord
    belongs_to :admin, optional: true
    belongs_to :main_course, optional: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :null_session
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_admin!, except: [:base,:about]
  def base_my_courses
    @main_courses = MainCourse.all
  end

  def about
  end

  def index_students
    @users = Admin.all
  end
end

app/controllers/main_courses_controller.rb
class MainCoursesController < ApplicationController
  before_action :set_main_course, only: %i[ show edit update destroy ]
  before_action :authenticate_admin!, except: [:index, :show]

  # GET /main_courses or /main_courses.json
  def index
    @main_courses = MainCourse.all
  end


  # GET /main_courses/1 or /main_courses/1.json
  def show
    @user = Admin.all
  end
  
  def enroll
  
    c = params[:c]
    course = MainCourse.find(c)
    seats = course.seats
    if seats > 0 
      if !Subscription.where(user_id: current_admin.id ,course_id: c).exists?
        s = Subscription.new
        s.update_attribute(:user_id, current_admin.id)
        s.update_attribute(:course_id, c)
        redirect_to request.referrer, :notice => "You are enrolled in this course!"
        course.seats = course.seats - 1
        course.save!
      else
        redirect_to request.referrer, :notice => "You are Already enrolled in this course!"
      end
    else
      redirect_to request.referrer, :notice => "No seats Available in this course"
    end
  end

  def deenroll
    c = params[:c]
    course = MainCourse.find(c)
    if Subscription.where(user_id: current_admin.id ,course_id: c).exists?
      Subscription.where(user_id:current_admin.id, course_id:c).destroy_all
      redirect_to request.referrer, :notice => "You are de-enrolled from this course!"
      course.seats = course.seats+1
      course.save!
    else
      redirect_to request.referrer, :notice => "You are Not enrolled in this course!"
    end
  end

  

  # GET /main_courses/new
  def new
    @main_course = MainCourse.new
  end

  # GET /main_courses/1/edit
  def edit
  end

  # POST /main_courses or /main_courses.json
  def create
    @main_course = MainCourse.new(main_course_params)

    respond_to do |format|
      if @main_course.save
        format.html { redirect_to @main_course, notice: "Main course was successfully created." }
        format.json { render :show, status: :created, location: @main_course }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @main_course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /main_courses/1 or /main_courses/1.json
  def update
    respond_to do |format|
      if @main_course.update(main_course_params)
        format.html { redirect_to @main_course, notice: "Main course was successfully updated." }
        format.json { render :show, status: :ok, location: @main_course }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @main_course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /main_courses/1 or /main_courses/1.json
  def destroy
    @main_course.destroy
    respond_to do |format|
      format.html { redirect_to main_courses_url, notice: "Main course was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_main_course
      @main_course = MainCourse.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def main_course_params
      params.require(:main_course).permit(:course_name, :course_id, :course_videos, :seats, :description,:enrolled)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/main_courses_helper.rb
module MainCoursesHelper
end

app/views/home/_header.html.erb
#<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
#<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<script src='https://kit.fontawesome.com/a076d05399.js' crossorigin='anonymous'></script>


<body>
<nav id="top" class="navbar navbar-expand-md navbar-light bg-light d-flex fixed-top">
  <a class="navbar-brand pl-3" style = "margin-left:8px;" href="#">
  <h1 class="h3 font-weight-bold"><%= image_tag ("logo.png") %></h1></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
  <span class="navbar-toggler-icon">
    <i id="icon" class="h3 fas fa-bars"></i>
  </span>
</button>
<style>
  a{
      text-decoration:none;
      color:grey;
      margin-right:2px;
  }
  a:Hover{
    color:#8364B4;
    background-color:transparent;
  }
</style>
<div class="collapse navbar-collapse justify-content-center" id="navbarNav">
  <ul class="navbar-nav">
    <% if admin_signed_in? && current_admin.admin %>
      <li class="nav-item h5 font-weight-normal px-3">
        <%= link_to 'Students', home_index_students_path,class:"nav-link"  %>
      </li>
    <% else %>
      <li class="nav-item h5 font-weight-normal px-3">
        <%= link_to 'About Us', home_about_path,class:"nav-link"  %>
      </li>
    <% end %>
      <li class="nav-item h5 font-weight-normal px-3">
       <%= link_to 'Courses', main_courses_path,class:"nav-link"  %>
      </li>
      <% if admin_signed_in? %>
       <li class="nav-item h5 font-weight-normal px-3">
        <%= link_to 'My Courses', root_path,class:"nav-link"  %>
       </li>
       <li class="nav-item h5 font-weight-normal px-3">
        <%= link_to "Sign Out", destroy_admin_session_path,method: :delete, class: "nav-link" %>
       </li>
       <li class="nav-item h5 font-weight-normal px-3">
        <%= link_to 'Edit My Profile', edit_admin_registration_path,class:"nav-link"  %>
       </li>
      <% else %>
       <li class="nav-item h5 font-weight-normal px-3">
        <%= link_to 'Log in', new_admin_session_path,class:"nav-link" %>
       </li>
       <li class="nav-item h5 font-weight-normal px-3">
        <%= link_to 'Sign Up', new_admin_registration_path,class:"nav-link" %>
       </li>
      <% end %>
    </ul>
</div>
  
<div class="social h4 pr-3">
  <a href="https://www.linkedin.com/company/devsnest/?originalSubdomain=in" class="px-2">
    <i class="fab fa-linkedin"></i>
  </a>
  <a href="https://www.instagram.com/devsnest.in/" class="px-2">
    <i class="fab fa-instagram"></i>
  </a>
  <a href="https://www.facebook.com/devsnest/" class="px-2">
    <i class="fab fa-facebook"></i>
  </a>
  </div>
</nav>
</body>

<script>
let icon = document.getElementById('icon');

icon.addEventListener('click', function(){ 
  icon.classList.toggle('fa-times');

});s
</script>

app/views/home/about.html.erb
<main>
<br/>
<br/>
<br/>
<br/>
<div class = "container">
 <h1 style = "color:white;">Welcome To Devsnest</h1>
</div>
</main>

app/views/home/base_my_courses.html.erb
<main>
<br/>
<br/>
<br/>
<br/>
<div class = "container">

  <div class="card">
    <div class="card-header">
      <h1>Courses</h1>
      <p id="notice"><%= notice %></p>
    </div>
    <div class="card-body">
      <div class = "row">
        <% @main_courses.each do |main_course| %>
          <% if Subscription.where(user_id: current_admin.id ,course_id: main_course.id).exists? %>
            <div class = "col-sm-4">
              <div class="card" style="width: 18rem;">
                <img  src="https://imgur.com/flXXKjM.jpg" class="card-img-top" alt="...">
                <div class="card-body">
                  <h5 class="card-title"><%= main_course.course_name %></h5>
                  <% if admin_signed_in? and current_admin.admin %>
                  <p class="card-text"><%= link_to 'Show Details', main_course %> | <%= link_to 'Edit', edit_main_course_path(main_course) %> | <%= link_to 'Destroy', main_course, method: :delete, data: { confirm: 'Are you sure?' } %></p>
                  <% else %>
                  <p class="card-text"><%= link_to 'Show Details', main_course %></p>
                  <% end %>
                  <%= link_to 'Enroll', main_courses_enroll_path(:c => main_course.id),class:"btn btn-outline-primary",method: :post  %>
                  <%= link_to 'De-enroll', main_courses_deenroll_path(:c => main_course.id),class:"btn btn-outline-danger",method: :post  %>
                </div>
              </div>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
  <br/>
</div>
</main>

app/views/home/index_students.html.erb
<main>
<br/>
<br/>
<br/>
<br/>
<div class = "container">
  <div class="card">
    <div class="card-header">
      <table class="table table-bordered table-stripeds table-hover">

          <thead class="thead-dark">
            <tr>
              <th>ID</th>
              <th>Email</th>
              <th>Created At</th>
            </tr>
          </thead>

          <tbody>
            <% if current_admin.admin %>
            <% @users.each do |user| %>
              <tr>
                <td><%= user.id %></td>
                <td><%= user.email %></td>
                
                <td><%= user.created_at %></td>
              </tr>
            <% end %>
            <% end %>
          </tbody>
        </table>
    </div>
  </div>
</div>
</main>

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= notice %>
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
   <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">

    <title>Devsnest</title>
    
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render 'home/header' %>
    <div>
    <br/>
    <% if notice %>
      <%= render 'layouts/alerts' %>
    <% end %>  
    <%= yield %>
    </div>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous"></script>
</html>

app/views/main_courses/_form.html.erb
<%= form_with(model: main_course) do |form| %>
  <% if main_course.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(main_course.errors.count, "error") %> prohibited this main_course from being saved:</h2>

      <ul>
        <% main_course.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :course_name %>
    <%= form.text_field :course_name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="field">
    <%= form.label :course_videos %>
    <%= form.text_field :course_videos %>
  </div>

  <div class="field">
    <%= form.label :seats %>
    <%= form.number_field :seats %>
  </div>

  <div class="actions">
    <%= form.submit class:"btn btn-dark"%>
  </div>
<% end %>

app/views/main_courses/edit.html.erb
<main>
<br/>
<br/>
<br/>
<br/>
  <div class = "container">
    <% if current_admin.admin %>
      <div class="card">
        <div class="card-header">
          <h1>Edit Course</h1>
        </div>
        <div class="card-body">

        <%= render 'form', main_course: @main_course %>

        <%= link_to 'Show', @main_course %> |
        <%= link_to 'Back', main_courses_path %>
        </div>
      </div>
    <% else %>
      <h1 style = "color:white;">Not Authorised</h1>
    <% end %>
  </div>
</main>

app/views/main_courses/index.html.erb
<main>
<br/>
<br/>
<br/>
<br/>
<div class = "container">
  <div class="card">
    <div class="card-header">
      <h1>Courses</h1>
      <p id="notice"><%= notice %></p>
    </div>
    <div class="card-body">
      <div class = "row">
        <% @main_courses.each do |main_course| %>
          <div class = "col-sm-4">
            <div class="card" style="width: 18rem;">
              <img  src="https://imgur.com/flXXKjM.jpg" class="card-img-top" alt="...">
              <div class="card-body">
                <h5 class="card-title"><%= main_course.course_name %></h5>
                <% if admin_signed_in? and current_admin.admin %>
                <p class="card-text"><%= link_to 'Show Details', main_course %> | <%= link_to 'Edit', edit_main_course_path(main_course) %> | <%= link_to 'Destroy', main_course, method: :delete, data: { confirm: 'Are you sure?' } %></p>
                <% else %>
                <p class="card-text"><%= link_to 'Show Details', main_course %></p>
                <% end %>
                <%= link_to 'Enroll', main_courses_enroll_path(:c => main_course.id),class:"btn btn-outline-primary",method: :post  %>
                <%= link_to 'De-enroll', main_courses_deenroll_path(:c => main_course.id),class:"btn btn-outline-danger",method: :post  %>
              </div>
            </div>
        </div>
    <% end %>
    </div>
    <br/>
    <% if admin_signed_in? && current_admin.admin %>
    <%= link_to 'Add Course', new_main_course_path,class: "btn btn-light" %>
    <% end %>
    </div>
  </div>
  <br/>
</div>
</main>

app/views/main_courses/mycourses.html.erb
<main>
<br/>
<br/>
<br/>
<br/>
<div class = "container">
  <div class="card">
    <div class="card-header">
      <h1>Courses</h1>
      <p id="notice"><%= notice %></p>
    </div>
    <div class="card-body">
      <div class = "row">
        <% @main_courses.each do |main_course| %>
          <div class = "col-sm-4">
            <div class="card" style="width: 18rem;">
              <img  src="http://www.simpleimageresizer.com/_uploads/photos/8584bc4e/logo.f1b45387_80x80.jpg" class="card-img-top" alt="...">
              <div class="card-body">
                <h5 class="card-title"><%= main_course.course_name %></h5>
                <% if admin_signed_in? and current_admin.admin %>
                <p class="card-text"><%= link_to 'Show', main_course %> | <%= link_to 'Edit', edit_main_course_path(main_course) %> | <%= link_to 'Destroy', main_course, method: :delete, data: { confirm: 'Are you sure?' } %></p>
                <% else %>
                <p class="card-text"><%= link_to 'Show', main_course %></p>
                <% end %>
                <%= link_to 'Enroll', main_courses_enroll_path(:c => main_course.id),class:"btn btn-outline-primary",method: :post  %>
                <%= link_to 'De-enroll', main_courses_deenroll_path(:c => main_course.id),class:"btn btn-outline-danger",method: :post  %>
              </div>
            </div>
          </div>
        <% end %>
      </div>
      <br/>
      <% if admin_signed_in? && current_admin.admin %>
      <%= link_to 'Add Course', new_main_course_path,class: "btn btn-light" %>
      <% end %>
   </div>
  </div>
  <br/>
</div>
</main>

app/views/main_courses/new.html.erb
<main>
<br/>
<br/>
<br/>
<br/>
<div class = "container">
  <div class="card">
    <div class="card-header">
      <h1>New Course</h1>
    </div>
    <div class="card-body">
      <%= render 'form', main_course: @main_course %>
      <%= link_to 'Back', main_courses_path %>
  </div>
</div>
</main>

app/views/main_courses/show.html.erb
<main>
<br/>
<br/>
<br/>
<br/>
<div class = "container">
  <div class="card">
    <div class="card-header">
      <h1>New Course</h1>
    </div>
  <div class="card-body">
    <p id="notice"><%= notice %></p>
    <p>
      <strong>Course name:</strong>
      <%= @main_course.course_name %>
    </p>
    <p>
      <strong>Description:</strong>
      <%= @main_course.description %>
    </p>
    <p>
      <strong>Course videos:</strong>
      <%= @main_course.course_videos %>
    </p>
    <p>
      <strong>Seats Available:</strong>
      <%= @main_course.seats %>
    </p>
    <% if admin_signed_in? && current_admin.admin %>
    <p>
      <strong>Students:</strong>

      <% @user.each do |user| %>
              <% if Subscription.where(user_id: user.id ,course_id: @main_course.id).exists? %>
              <li>
                <%= user.email  %>
                </li>
              <% end %>
      <% end %>
   </p>
   <% end %>
  <% if admin_signed_in? && current_admin.admin %>
   <%= link_to 'Edit', edit_main_course_path(@main_course) %> |
   <%= link_to 'Back', main_courses_path %>
  <% end %>
</div>
</main>